### ISSUE TITLE
First lesson. Cant do "docker-compose up"

### ISSUE THREAD

**Issue by Vdyuk** [ParrotPrediction/docker-course-xgboost#3]
Hello. I'm on Windows 7. There are my steps in Lesson "Getting rocket off the ground":
1) I did  "git clone https://github.com/ParrotPrediction/docker-course-xgboost" in git bash terminal
2) Setup docker 
3) $ cd docker-course-xgboost
4) $ docker -v
Docker version 1.13.1, build 092cba3
5) $ docker-compose -v
docker-compose version 1.11.1, build 7afaa436
6) $ docker-compose up
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
............................
  File "site-packages\docker\transport\npipeconn.py", line 31, in connect
  File "site-packages\docker\transport\npipesocket.py", line 22, in wrapped
  File "site-packages\docker\transport\npipesocket.py", line 50, in connect
pywintypes.error: (2, 'WaitNamedPipe', '\xcd\xe5 \xf3\xe4\xe0\xe5\xf2\xf1\xff \xed\xe0\xe9\xf2\xe8 \xf3\xea\xe0\xe7\xe0\xed\xed\xfb\xe9 \xf4\xe0\xe9\xeb.')
Failed to execute script docker-compose

What should I do to fix problem?

**Comment by khozzy** [comment]
Hello, it seems to be a problem with Docker on Windows. Please look at this threads, maybe they will help 
- https://github.com/laradock/laradock/issues/565
- https://github.com/IBM-Blockchain/fabric-images/issues/19

**Comment by stoneyv** [comment]
I have a similar problem on Ubuntu 16.04 where docker-compose is complaining about a field in the docker-compose.yml file.  On Ubuntu 16.04 the repository has an older docker-compose version 1.5.2  I tried to remove the older version and add a requirement for >=1.6.0, but it doesn't exist.  I will probably need to download a source package and headers and build it myself.
```  
stoney@laptop2:~/Desktop/docker-course-xgboost$ docker-compose up
ERROR: In file './docker-compose.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.
```

**Comment by zeapo** [comment]
I had a similar problem. The issue was that the environment was not configured. Check that `docker ps` works.

**Comment by stoneyv** [comment]
I needed to add the user to the docker group
sudo usermod -a -G docker $USER
